<?php

namespace ContainerNmOxUW0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SubscriptionsController' shared autowired service.
     *
     * @return \App\Controller\SubscriptionsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SubscriptionsController.php';

        $container->services['App\\Controller\\SubscriptionsController'] = $instance = new \App\Controller\SubscriptionsController(($container->privates['App\\Repository\\SubscriptionsRepository'] ?? $container->load('getSubscriptionsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\SubscriptionsController', $container));

        return $instance;
    }
}
