<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL95Us8n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL95Us8n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL95Us8n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL95Us8n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL95Us8n\App_KernelDevDebugContainer([
    'container.build_hash' => 'L95Us8n',
    'container.build_id' => 'f7f7110d',
    'container.build_time' => 1678258055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL95Us8n');
