<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNmOxUW0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNmOxUW0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNmOxUW0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNmOxUW0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNmOxUW0\App_KernelDevDebugContainer([
    'container.build_hash' => 'NmOxUW0',
    'container.build_id' => '15514cf5',
    'container.build_time' => 1677680533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNmOxUW0');
