<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_forgot_password_request' => [[], ['_controller' => 'App\\Controller\\ResetPasswordController::request'], [], [['text', '/reset-password']], [], [], []],
    'app_check_email' => [[], ['_controller' => 'App\\Controller\\ResetPasswordController::checkEmail'], [], [['text', '/reset-password/check-email']], [], [], []],
    'app_reset_password' => [['token'], ['token' => null, '_controller' => 'App\\Controller\\ResetPasswordController::reset'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/reset-password/reset']], [], [], []],
    'app_subscriptions' => [[], ['_controller' => 'App\\Controller\\SubscriptionsController::index'], [], [['text', '/subscriptions']], [], [], []],
    'create_subscriptions' => [[], ['_controller' => 'App\\Controller\\SubscriptionsController::create'], [], [['text', '/subscriptions/create']], [], [], []],
    'edit_subscription' => [['id'], ['_controller' => 'App\\Controller\\SubscriptionsController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/subscriptions/edit']], [], [], []],
    'delete_subscription' => [['id'], ['_controller' => 'App\\Controller\\SubscriptionsController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/subscriptions/delete']], [], [], []],
    'app_superadmin' => [[], ['_controller' => 'App\\Controller\\SuperadminController::index'], [], [['text', '/superadmin']], [], [], []],
];
